NEKO_GIFS = [
    "CgACAgQAAxkBAAIJ4WDeBL82ICtTdICx6NmC3t77XNteAAJmAgACKT6UUmsjgII0_MxQIAQ",
    "CgACAgUAAxkBAAIJ4mDeBL_fruuMXpl90mtywNWpGUTeAAJlAgACixeIVtzckFrsUQoYIAQ",
    "CgACAgQAAxkBAAIJ42DeBL8KxrMB7E0yuxojltB57GTlAAJhAgACexyMUsJhXJ12oeLJIAQ",
    "CgACAgQAAxkBAAIJ5GDeBL8Z6SQltLX1AcTYIModtgotAAJ1AgACYFeMUlsH7aBsTIJsIAQ",
    "CgACAgUAAxkBAAIJ5WDeBL9OB__LyNt31VHWk5sZ-QFJAAIXAgACa4wgVfRALG3vKEj3IAQ",
    "CgACAgQAAxkBAAIJ5mDeBL8zUQ7yVR5RPlNAfXEUtk67AAKPAgACqN69UdUnV2qpeZVsIAQ",
    "CgACAgQAAxkBAAIJ52DeBL8P8NeV039N54dgySsYbriRAAJVAgACsx2UUr0joi8r6Wk1IAQ",
    "CgACAgQAAxkBAAIJ6GDeBL8NPU_ROYR9Ty-rIHCa0cPhAAKwAgAC3BIlUgABIeW601qZPSAE",
    "CgACAgQAAxkBAAIJ6WDeBL9OER_VyjVXadb8PCe7g13xAAJyAgACRCiNULIN3-yqjEPTIAQ",
    "CgACAgQAAxkBAAIJ6mDeBL8PuBBIVbt6GZAAAZYkOugRoAACZAIAAladhVJC_bCPOPZwVSAE"
  ]



NEKO_TEXT = [
     "@weebarsh, the Neko, Scratches you!",
     "Nya! {user1} is a Neko!"
   ]
     
