NEKO_GIFS = [
      "CgACAgQAAx0CS3FrwgABA7QRYN4Qh3gRt9W7EyBclz66lrnRCLEAAlwCAAILXpRS0AXMoo4Mt0ggBA",
      "CgACAgQAAx0CS3FrwgABA7QTYN4QoQU5h6x3dVKWHhpxjof7dGYAAm4CAAImOp1SFu9fLxqQHTsgBA",
      "CgACAgQAAx0CS3FrwgABA7QXYN4Qr5diE0lFazb_nICRWcBky1QAAg4CAALeXaRSOV07ULDF8w8gBA",
      "CgACAgQAAx0CS3FrwgABA7QZYN4QvcRQpB6MyQnC-CKwb0ADw5IAAgUCAAKtg_1Sc1ruipBl-HIgBA",
      "CgACAgQAAx0CS3FrwgABA7QgYN4Q9JgbGGR4HmUcQNIJz43sj1wAAm0CAALlRpRSq6xYmzCCBkQgBA",
      "CgACAgQAAx0CS3FrwgABA7QqYN4RI1V6naPXjecKOXTH049L2ooAAk0CAAJ4gJVSS4rpSvu5Gm0gBA",
      "CgACAgQAAx0CS3FrwgABA7QsYN4RNJjg3TZwzS8EXAt4pbWcyxQAAmgCAAIwnI1S782tAAEVB6kOIAQ",
      "CgACAgQAAx0CS3FrwgABA7QvYN4RXiwVjyPjIXQTDipkUbzYL1wAAhMCAALzhZxSIVpg1Ofqc9MgBA",
      "CgACAgQAAx0CS3FrwgABA7QxYN4RdbMRIghDm2rdTUv8lDTwImkAAnUCAAJxod1S2ON4j8DhPRggBA",
      "CgACAgQAAx0CS3FrwgABA7QzYN4RjoFTcPK4m6uYv7YrY7PEEh0AAk8CAAIKeKRSrRPpeh2C9XQgBA"
   ]



NEKO_TEXT = [
     "@weebarsh, the Neko, Scratches you!",
     "Nya! {user1} is a Neko!",
     "My Heart Goes Meow😻",
     "Neko Neko Niii!"
     "{user1} nyaed {user2}"
   ]
     
CATTO_GIFS = [
     "CgACAgQAAxkBAAIJ_2DeKUy5t1snrwG5JLFMjUc-8uLbAALLBwACBdNQU1arAX5_1F_7IAQ",
     "CgACAgIAAxkBAAIKAWDeKVb0U7CcjMa9CeJdDxpaWZbUAAJ4CgACJYfJSlV3Kl5rpvBxIAQ",
     "CgACAgQAAxkBAAIKAAFg3ilR2PkQOXYNmDDkOnYbE5McXAACjwIAAqjevVHVJ1dqqXmVbCAE",
     "CgACAgQAAxkBAAIKAmDeKVvPemPy0nznKEj0HTl2XntbAAK3AgAC62NsURUCu8Fufv1SIAQ",
     "CgACAgQAAxkBAAIKA2DeKWHmgoz28Ln2m0zbnm5XJxQ4AAJVAgACsx2UUr0joi8r6Wk1IAQ",
     "CgACAgQAAxkBAAIKBGDeKWef8xHiF017pg3yfKKulCknAAKwAgAC3BIlUgABIeW601qZPSAE",
     "CgACAgQAAxkBAAIKBWDeKWwS2lfVRh_SffXbxZvG34ZGAAJAAgACoNmFUhHMKYTMCDTEIAQ",
     "CgACAgQAAxkBAAIKBmDeKXFdBFSPHgGShQl_4wt4fQvYAAJyAgACRCiNULIN3-yqjEPTIAQ",
     "CgACAgQAAxkBAAIKB2DeKXd0oBthVOKTlnE9IRx3vZO0AAJkAgACVp2FUkL9sI849nBVIAQ",
     "CgACAgUAAxkBAAIKCGDeIAMDOcdV6ILZ9vw6KPA-Z6lQAAJMAAPix0lUneXvfTnra18gBA"
    ]


CATTO_TEXT = [
      "Cat Is Sleeping Nya!",
      "Catto Just Scratched you",
      "@weebarsh is the Catto Lord",
      "Catto is playing with @izumibotofficial now!",
      "Catto Loves You ❤"
    ]
