RUN_STRINGS = (
    "Now you see me, now you don't."
    "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "Get back here!",
    "REEEEEEEEEEEEEEEEEE!!!!!!!",
    "Look out for the wall!",
    "Don't leave me alone with them!!",
    "You've got company!",
    "Chotto matte!",
    "Yare yare daze",
    "*Naruto run activated*",
    "*Nezuko run activated*",
    "Hey take responsibilty for what you just did!",
    "May the odds be ever in your favour.",
    "Run everyone, they just dropped a bomb 💣💣",
    "And they disappeared forever, never to be seen again.",
    "Legend has it, they're still running.",
    "Hasta la vista, baby.",
    "Ah, what a waste. I liked that one.",
    "As The Doctor would say... RUN!",
)

TRUTH_STRINGS = (
    "Have you ever been caught checking something out?",
    "When’s the last time you lied to your parents and why?",
    "Have you ever picked your nose and eaten it?",
    "If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?",
    "When was the last time you lied?",
    "When was the last time you cried and why?",
    "What's your biggest fear?",
    "What's your biggest fantasy?",
    "Do you have any fetishes?",
    "What's something you're glad your mum doesn't know about you?",
    "Have you ever cheated on someone?",
    "What's the worst thing you've ever done?",
    "What was the last thing you searched for on your phone?",
    "After you've dropped a piece of food, what's the longest time you've left it on the ground and then ate it?",
    "What is your guilty pleasure?",
    "What is your worst habit?",
    "Do you sing in the shower?",
    "Do you ever talk to yourself in the mirror?",
    "What is your go-to song for the shower?",
    "What don't you like about yourself?",
    "Would you rather live with no internet or no A/C or heating?",
    "If someone offered you $1 million to break up with your girlfriend/boyfriend, would you do it?",
    "If you were reborn, what decade would you want to be born in?",
    "If you could go back in time in erase one thing you said or did, what would it be?",
    "Has your boyfriend or girlfriend ever embarrassed you?",
    "If you could suddenly become invisible, what would you do?",
    "Have you ever been caught checking someone out?",
    "Have you ever waved at someone thinking they saw you when really they didn't? What did you do when you realized it?",
    "What's the longest time you've stayed in the bathroom, and why did you stay for that long?",
    "Have you ever cried because you missed your parents so much?",
    "Would you rather be caught picking your nose or picking a wedgie?",
    "Describe the strangest dream you've ever had. Did you like it?",
    "Have you ever posted something on social media that you regret? If yes then what was that about?",
    "Have you ever ding dong ditched someone?",
    "The world ends next week, and you can do anything you want (even if it's illegal). What would you do?",
    "Would you wear your shirt inside out for a whole day if someone paid you $100?",
    "What is the most childish thing that you still do?",
    "How far would you go to land the guy or girl of your dreams?",
    "Tell us about a time you embarrassed yourself in front of a crush.",
    "Have you ever kept a library book?",
    "Who is one person you pretend to like, but actually don’t?",
    "What children’s movie could you watch over and over again?",
    "Do you have bad foot odor?",
    "Do you have any silly nicknames?",
    r"When was the last time you wet the bed? \o/",
    "How many pancakes have you eaten in a single sitting?",
    "Have you ever intentionally hit someone with your car or bicycle? If yes then why? (6_9)",
    "If you had to make out with any Disney character, who would it be?",
    "Have you ever watched a movie you knew you shouldn’t?",
    "Have you ever wanted to try LARP (Live Action Role-Play)?",
    "What app on your phone do you waste the most time on?",
    "Have you ever pretended to be sick to get out of something? If so, what was it?",
    "What is the most food you’ve eaten in a single sitting?",
    "Do you dance when you’re by yourself?",
    "What song on the radio or your smartphone do you sing with every time it comes on?",
    "Do you own a pair of footie pajamas?",
    "Are you scared of the dark?",
    "What ‘As seen on TV’ product do you secretly want to buy?",
    "Do you still take bubble baths?",
    "If you were home by yourself all day, what would you do?",
    "How many selfies do you take a day?",
    "What is something you’ve done to try to be ‘cooler’?",
    "When was the last time you brushed your teeth? (-_-)",
    "Have you ever eaten something off the floor?",
    "Do you like hanging out with your parents?",
    "What is something that no one else knows about you? (6_9)",
                                                            
     )

DARE_STRINGS = (
    "Make up a story about any item that comes in your mind *right now*",
    "Tell us about an incident that happened in your life recently!\nP.S. It can be anything -> like funny, surprising story, tragedy etc. *",
    "Think about a word starts with T and it must be longer then 6 letters. After that Write that word *backwards* in 17 seconds",
    "Think about a word starts with A and it must be longer then 5 letters. After that Write that word *backwards* in 17 seconds",
    "Think about a word starts with S and it must be longer then 6 letters. After that Write that word *backwards* in 17 seconds",
    "Think about a word starts with B and it must be longer then 6 letters. After that Write that word *backwards* in 17 seconds",
    "Think about a word starts with T and it must be longer then 6 letters. After that Write that word *backwards* in 17 seconds",
    "Think about a word starts with T and it must be longer then 8 letters. After that Write that word *backwards* in 17 seconds",
    "Think about a word starts with E and it must be longer then 6 letters. After that Write that word *backwards* in 17 seconds",

     )

IGRIS_IMG = (
     "https://telegra.ph/file/17f7cf494420f54a4c53a.jpg",
     "https://telegra.ph/file/aebd88f3b99e53e144f63.jpg",
     "https://telegra.ph/file/2f4a5342b4e5a11f79b3a.jpg",
     "https://telegra.ph/file/6ae266b389380d0edc23b.jpg"

     ) 

CUTVEIN_IMG = (
     "https://i.imgur.com/oMZKEhh.jpg",
     "https://i.imgur.com/O6GMp5h.jpg",
     "https://i.imgur.com/FE2hhCH.jpg",
     "https://i.imgur.com/HmDi7Cr.jpg"

     )

INSULT_STRINGS = [
    "Owww ... Such a stupid idiot.",
    "Don't drink and type.",
    "I think you should go home or better a mental asylum.",
    "Do you realize you are making a fool of yourself? Apparently not.",
    "You can type better than that.",
    "Sorry, we do not sell brains.",
    "Believe me you are not normal.",
    "I bet your brain feels as good as new, seeing that you never use it.",
    "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
    "Zombies eat brains...\nyou're safe.",
    "You didn't evolve from apes,\n...they evolved from you.",
    "Come back and talk to me when your I.Q. exceeds your age.",
    "I'm not saying you're stupid, I'm just saying you've got bad luck when it comes to thinking.",
    "What language are you speaking? Cause it sounds like bullshit.",
    "Stupidity is not a crime so you are free to go.",
    "You are proof that evolution CAN go in reverse.",
    "I would ask you how old you are but I know you can't count that high.",
    "As an outsider, what do you think of the human race?",
    "Brains aren't everything. In your case they're nothing.",
    "Usually people live and learn. You just live.",
    "I don't know what makes you so stupid, but it really works.",
    "Keep talking, someday you'll say something intelligent!\nI doubt it though.",
    "Shock me, say something intelligent.",
    "Your IQ's lower than your shoe size.",
    "Alas! Your neurotransmitters are no more working.",
    "Everyone has the right to be stupid but you are abusing the privilege.",
    "I'm sorry I hurt your feelings when I called you stupid.\nI thought you already knew that.",
    "You should try tasting cyanide.",
    "Your enzymes are meant to digest rat poison.",
    "You should try sleeping forever.",
    "You could make a world record by jumping from a plane without parachute.",
    "Stop talking BS and jump in front of a running bullet train.",
    "Try bathing with Hydrochloric Acid instead of water.",
    "You should definitely try this:\nif you hold your breath underwater for an hour, you can then hold it forever.",
    "Go Green!\nStop inhaling Oxygen.",
    "God was searching for you.\nYou should leave to meet him.",
    "give your 100%.\nNow, go donate blood.",
    "Try jumping from a hundred story building but you can do it only once.",
    "You should donate your brain seeing that you never used it.",
    "Volunteer for target in an firing range.",
    "Head shots are fun.\nGet yourself one.",
    "You should try swimming with great white sharks.",
    "You should paint yourself red and run in a bull marathon.",
    "You can stay underwater for the rest of your life without coming back up.",
    "How about you stop breathing for like 1 day?\nThat'll be great.",
    "Try provoking a tiger while you both are in a cage.",
    "Have you tried shooting yourself as high as 100m using a canon.",
    "You should try holding TNT in your mouth and igniting it.",
    "Try playing catch and throw with RDX its fun.",
    "I heard phogine is poisonous but i guess you wont mind inhaling it for fun.",
    "Launch yourself into outer space while forgetting oxygen on Earth.",
    "You should try playing snake and ladders, with real snakes and no ladders.",
    "Dance naked on a couple of HT wires.",
    "Active Volcano is the best swimming pool for you.",
    "You should try hot bath in a volcano.",
    "Try to spend one day in a coffin and it will be yours forever.",
    "Hit Uranium with a slow moving neutron in your presence. It will be a worthwhile experience.",
    "You can be the first person to step on sun. Have a try.",
]

IGRIS_STRINGS = (
      "YES Human, tell me", 
      "You remembered me?", 
      "Pshycho Demon is here!", 
      "I Only Serve To the Devil, JUST KIDDING", 
      "When is our next Gamble?", 
      "*You have Summoned the most Powerful pshycho Demon*", 
      "STOP calling ME if you don't wanna gamble", 
      "Here we go again", 
      "Yumeko,*Joined the Gambling Area*", 
      "Yaaaaaaa?", 
      "Yumeko.EXE STOPPED WORKING", 
      "Okay, Let's Go", 
      "Let's do this", 
      " Boring ", 
      "Hold up, Coming"
    
      ) 
     
IGRIS_PHOTO = (
    "https://wallpapercave.com/wp/wp2164441.jpg") 


GIFS = [
    'CgACAgUAAx0EVmwfqQACElhfo3yZv1njCC11INcQSAi4UlN8vwACqwADg_8wVeGSv41OYU6zHgQ',
    'CgACAgUAAx0CVmwfqQACEoZfo4AAAcduM428ax1T0y-zo1tXdFUAAlUBAAJu09hWrXoj81vn9B8eBA',
    'CgACAgQAAx0CVmwfqQACEodfo4AAAdRGH1X6XUseFvY1X6raVGkAAmgIAAJWQ9FR6NdhTVfyDzgeBA', 
    'CgACAgQAAxkBAAN4X7oiKAOFtoB2nH-3GRCTclxJapsAAm4CAAKUq5VSwanbaqA_tZceBA', 
    'CgACAgQAAxkBAAN5X7oiMA8mY1BZGp5I4VdfoDg-oH8AAksCAAIstI1SCcfAOJunTIEeBA'
]

SLAP_EMILIA_TEMPLATES = (
    "Slap me one more time and I'll mute you.",
    "Stop slapping me. REEEEEEEEEEEEEE.",
    [
        "I am muting you for a minute.",  # normal reply
        "Stop slapping me just because I can't mute you. REEEEEEEEEE.",  # reply to admin
        "tmute",  # command
        "Shut up!",
        "Silence!"
    ])

SLAP_TEMPLATES = (
    "{user2} was killed for loosing gamble.",
    "{user2} starved without pats.",
    "{user2} was knocked into the void by {user1}.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} got rekt.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user1} spammed {user2}'s email.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    r"( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
    "GOKAGE Used his S Rank Skills and slap {user2} out of the planet.",
    "{user2} ate a bat and discovered a new disease.",
    "{user1} folded {user2} into a paper plane",
    "{user1} served {user2} some bat soup.",
    "{user2} was sent to his home, the planet of the apes.",
    "{user1} kicked {user2} out of a moving train.",
    "{user2} just killed John Wick’s dog.",
    "{user1} performed an Avada Kedavra spell on {user2}.",
    "{user1} subjected {user2} to a fiery furnace.",
    "Sakura Haruno just got more useful than {user2}",
    "{user1} unplugged {user2}'s life support.",
    "{user1} subscribed {user2}' to 5 years of bad internet.",
    "Zekxx Threw his Demon Sword on {user2}!",
    "{user1} took all of {user2}'s cookies.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} lost his race piece!",  #No game no life reference
    "Shut up {user2}, you are just {user2}.",  #No game no life reference
    "{user1} hits {user2} with Aka si anse!",  #No game no life reference
    "@NeoTheKitty scratches {user2}",  #Pixels pet cat - @NeoTheKitty 
    "Majin buu ate {user2}",  #Dbz
    "Goblin slayer slays {user2}",  #Goblin Slayer
)

PAT_TEMPLATES = (
    "{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA", 
    "CgACAgQAAxkBAAO5X7olTkYuRTw1AV__6mFehORkP4QAAiMCAAI3KIxSjBqOTuo4xf0eBA", 
    "CgACAgQAAxkBAAO6X7olTklDbgs9nr5bNbM9xy0uunUAAmACAAL1G4xSKOH5wmDvxy4eBA", 
    "CgACAgQAAxkBAAIViWDBew94TiaL_c9HyX0xpUY8wFy2AAJKAgACMU80Urc2Hvh_WMDeHwQ",
    "CgACAgQAAxkBAAO7X7olTq_mAur7bsieTD5QnyQ06rUAAlwCAAINjoRSWyAJKJ9n2moeBA") 

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ", 
    "CAACAgQAAxkBAAPCX7ol0GGF-58u9AfabFk_16ehVXEAArUAA9UzMwuz7SpKK9TonB4E",
    "CAACAgQAAxkBAAPDX7ol2ixI5WdJ48h8rQYbc__6KisAAt8AA9UzMwusEnTVQ5yoAh4E", 
    "CAACAgQAAxkBAAPEX7ol55uzT-EkbHOkA-_94MiMcBgAAvAAA9UzMws7KHpoG8wBjh4E") 

IGRIS_STICKERS = (
      "CAACAgUAAxkBAAIDQF-7_69odiU6ityjRjqRcknwgEi4AAKRAANpkK04stJbSpXkS-geBA",
      "CAACAgUAAxkBAAIDP1-7_6lnPR1y5P7R6BqCBHEsyL2WAAKQAANpkK045aq_E5n7-ogeBA", 
      "CAACAgUAAxkBAAIDPl-7_6MG9sSVGmdnXXKbofCqhHl6AAKPAANpkK047gg7KKlXdb4eBA", 
      "CAACAgUAAxkBAAIDPV-7_6CbPPi7U2Bz27SQFgQPWlM8AAKOAANpkK04CM9qcoyutvceBA") 

PING_STRING = (
    " PONG!!! ", 
    "I am here!",
)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
    "Demon sword", 
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

EYES = [['⌐■', '■'], [' ͠°', ' °'], ['⇀', '↼'], ['´• ', ' •`'], ['´', '`'],
        ['`', '´'], ['ó', 'ò'], ['ò', 'ó'], ['⸌', '⸍'], ['>',
                                                         '<'], ['Ƹ̵̡', 'Ʒ'],
        ['ᗒ', 'ᗕ'], ['⟃', '⟄'], ['⪧', '⪦'], ['⪦', '⪧'], ['⪩', '⪨'], ['⪨', '⪩'],
        ['⪰', '⪯'], ['⫑', '⫒'], ['⨴', '⨵'], ['⩿', '⪀'], ['⩾', '⩽'], ['⩺', '⩹'],
        ['⩹', '⩺'], ['◥▶', '◀◤'], ['◍', '◎'], ['/͠-', '┐͡-\\'], ['⌣', '⌣”'],
        [' ͡⎚', ' ͡⎚'], ['≋'], ['૦ઁ'], ['  ͯ'], ['  ͌'], ['ළ'], ['◉'], ['☉'],
        ['・'], ['▰'], ['ᵔ'], [' ﾟ'], ['□'], ['☼'], ['*'], ['`'], ['⚆'], ['⊜'],
        ['>'], ['❍'], ['￣'], ['─'], ['✿'], ['•'], ['T'], ['^'], ['ⱺ'], ['@'],
        ['ȍ'], ['  '], ['  '], ['x'], ['-'], ['$'], ['Ȍ'], ['ʘ'], ['Ꝋ'],
        [''], ['⸟'], ['๏'], ['ⴲ'], ['◕'], ['◔'], ['✧'], ['■'], ['♥'], [' ͡°'],
        ['¬'], [' º '], ['⨶'], ['⨱'], ['⏓'], ['⏒'], ['⍜'], ['⍤'], ['ᚖ'], ['ᴗ'],
        ['ಠ'], ['σ'], ['☯']]

MOUTHS = [['v'], ['ᴥ'], ['ᗝ'], ['Ѡ'], ['ᗜ'], ['Ꮂ'], ['ᨓ'], ['ᨎ'],
          ['ヮ'], ['╭͜ʖ╮'], [' ͟ل͜'], [' ͜ʖ'], [' ͟ʖ'], [' ʖ̯'], ['ω'], [' ³'],
          [' ε '], ['﹏'], ['□'], ['ل͜'], ['‿'], ['╭╮'], ['‿‿'], ['▾'], ['‸'],
          ['Д'], ['∀'], ['!'], ['人'], ['.'], ['ロ'], ['_'], ['෴'], ['ѽ'], ['ഌ'],
          ['⏠'], ['⏏'], ['⍊'], ['⍘'], ['ツ'], ['益'], ['╭∩╮'], ['Ĺ̯'], ['◡'],
          [' ͜つ']]

EARS = [
    ['q', 'p'],
    ['ʢ', 'ʡ'],
    ['⸮', '?'],
    ['ʕ', 'ʔ'],
    ['ᖗ', 'ᖘ'],
    ['ᕦ', 'ᕥ'],
    ['ᕦ(', ')ᕥ'],
    ['ᕙ(', ')ᕗ'],
    ['ᘳ', 'ᘰ'],
    ['ᕮ', 'ᕭ'],
    ['ᕳ', 'ᕲ'],
    ['(', ')'],
    ['[', ']'],
    ['¯\\_', '_/¯'],
    ['୧', '୨'],
    ['୨', '୧'],
    ['⤜(', ')⤏'],
    ['☞', '☞'],
    ['ᑫ', 'ᑷ'],
    ['ᑴ', 'ᑷ'],
    ['ヽ(', ')ﾉ'],
    ['\\(', ')/'],
    ['乁(', ')ㄏ'],
    ['└[', ']┘'],
    ['(づ', ')づ'],
    ['(ง', ')ง'],
    ['⎝', '⎠'],
    ['ლ(', 'ლ)'],
    ['ᕕ(', ')ᕗ'],
    ['(∩', ')⊃━☆ﾟ.*'],
]

TOSS = (
    "Heads",
    "Tails",
    "Yumeko sent coin to Hell", 
)

DECIDE = ("Yes.", "No.", "Maybe.", " Ask Devil.","Don't ask me.")

TABLE = ("(╯°□°）╯彡 ┻━┻", "I ran out of tables, will order more.",
         "Go do some work instead of flippin tables.")
